### ISSUE TITLE
[v1.0.1 Launcher Bug] $NewPlayerAlias is empty

### ISSUE THREAD

**Issue by PGHJA991id12** [LANCommander/LANCommander#123]
As title says.

**Comment by PGHJA991id12** [comment]
I noticed that the Name Change script runs upon running the game, and that's when $NewPlayerAlias is empty. 

Name Change script on Install still works as intended.

**Comment by pathartl** [comment]
Confirmed. Got a fix ready, will be deployed with v1.0.2
