### ISSUE TITLE
Download queueing not working

### ISSUE THREAD

**Issue by jpaussa** [LANCommander/LANCommander#131]
When there is a game downloading if you try to install another game it will say it is queued to download but never starts. 
![Screenshot 2024-10-20 132326](https://github.com/user-attachments/assets/5e8e315f-fc4b-47d3-9eec-07077e181434)

**Comment by jpaussa** [comment]
![Screenshot 2024-10-20 132629](https://github.com/user-attachments/assets/ff6670b8-8051-4ff5-b216-bf2d521cb539)

**Comment by pathartl** [comment]
Thanks for reporting! It will be fixed in v1.0.4.
