### ISSUE TITLE
Registration fails with Unauthorized when password not complex enough

### ISSUE THREAD

**Issue by jpaussa** [LANCommander/LANCommander#132]
When trying to register with a simple password it shows an unauthorized error. Put in a more complex password (letmein69) and was able to register. Ideally there would be a more descriptive error. 

![Screenshot 2024-10-20 132747](https://github.com/user-attachments/assets/df370ba3-6b3a-4f24-99b3-e28a0aa51473)

**Comment by jpaussa** [comment]
Error looks correct when using the website, seems to be launcher related.
![2024-10-21-201310_485x665_scrot](https://github.com/user-attachments/assets/2bb048ed-d75c-412b-bc44-e67b24cae17b)

**Comment by pathartl** [comment]
Thanks for the report! This will be fixed in v1.0.4.
