### ISSUE TITLE
Just wanted to share my sample Dockerfile and share some feedback

### ISSUE THREAD

**Issue by sneJ-** [LANCommander/LANCommander#31]
Hi,

first of all thank you for sharing your project. It looks really neat and I'm looking forward to try it on my next LAN party.

I just wanted to share my sample Dockerfile for your project. It works well with the `v0.1.3` release.
Only the dashboard page isn't working, which isn't that big of a deal, as all the other pages work.
As far as of my reasarch the dashboard uses dotnet methods that aren't supported in Linux or Mac. (`System.PlatformNotSupportedException: Performance Counters are not supported on this platform.`)
I usually log in and then manually switch to the `/Games` page to add games etc.

Here is the Dockerfile I used:
```Dockerfile
FROM debian:stable-slim as builder

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    curl wget git ca-certificates gnupg && \
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb && \
    apt-get update && apt-get install -y dotnet-sdk-7.0 && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    NODE_MAJOR=20 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && apt-get install nodejs -y

RUN cd /opt && git clone https://github.com/LANCommander/LANCommander.git && cd LANCommander && git checkout v0.1.3
WORKDIR /opt/LANCommander
RUN dotnet restore && cd LANCommander/wwwroot/scripts && npm install && cd /opt/LANCommander && \
    dotnet build "./LANCommander/LANCommander.csproj" --no-restore /p:Version="0.1.3" && \
    dotnet publish "./LANCommander/LANCommander.csproj" -c Release -o _Build --self-contained --os linux -p:PublishSignleFile=true

FROM debian:stable-slim

RUN apt-get update && apt-get install -y wget && wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb && apt-get update && apt-get install -y aspnetcore-runtime-7.0
COPY --from=builder /opt/LANCommander/_Build /opt/LANCommander
WORKDIR /opt/LANCommander

EXPOSE 1337

CMD /opt/LANCommander/LANCommander
```

I start the Container with:
```sh
docker run -it -p 1337:1337 lancommander:0.1.3
```

For future releases it would be great if all the folders that contain data that can be changed by the user would be stored in one top level folder. Or if there would be a configuration option do do this.

For example, that all the variable data is stored in a `data` folder:
```
- data/
--- Logs/
--- Saves/
--- Snippets/
--- Uploads/
--- LANCommander.db
...
```

If the folder structure would be changed like this, one would be able to use Docker's volume mount feature more easily to store these kinds of data outside of the Container persistently.

**Comment by pathartl** [comment]
Massive thanks for getting started on this!

There are essentially two parts of LANCommander that have used .NET APIs that are only supported on Windows:

- The dashboard utilizes PerformanceCounters to chart information such as total system CPU usage, RAM allocation, and NIC transfer rates
- Specifying a .ico or .exe for the icon on a game will use System.Drawing.Icon to extract an icon and convert it to a PNG

With the introduction of [0.2.1](https://github.com/LANCommander/LANCommander/releases/tag/v0.2.1) the latter has been replaced by Media and there are no longer any references to System.Drawing.Icon. Part of this was an effort to make the application multi-platform friendly.

Future versions of the application will only include the dashboard on Windows and Linux builds will be provided with each release. Once this happens I might try to reach out to the folks over at linuxserver.io to see if they'd be willing to maintain a Docker container.

To address your other concern, the following folder paths can be changed via `Settings.yml` or via the settings interface as of 0.2.1:

- Saves
- Archives (Default is Uploads)
- Media

I think the proper approach might be to allow for a command line parameter to specify a prefix for all data storage pathing. This is not something I've considered until now, so it'll take some rework to get it right.

**Comment by sneJ-** [comment]
Thanks for the tip with the `settings.yml`. I'm able to configure my Docker Container properly with it and am able to persist data easily between Container restarts.

I just created a sample repo with some instructions on how to run with Docker in Linux.
https://github.com/sneJ-/LANCommander-docker/tree/master

Hope you don't mind. Feel free to copy anything from there you like. :-)
