### ISSUE TITLE
Notes are not sent to playnite

### ISSUE THREAD

**Issue by bhaptiste** [LANCommander/LANCommander#47]
Hello,

Notes in General tab are not sent to playnite.
![image](https://github.com/LANCommander/LANCommander/assets/153960467/81b9a109-d243-462a-98a0-44b61c4b8833)

In playnite :
![image](https://github.com/LANCommander/LANCommander/assets/153960467/bad3c4a0-2899-4729-a6b4-62c36b651a89)

**Comment by pathartl** [comment]
This will be included in the next release
