### ISSUE TITLE
Difficult to know allowed filetypes

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#49]
![msedge_QZ5HkO8ssM](https://github.com/LANCommander/LANCommander/assets/5581855/e04aba61-0688-41ad-8b1c-39576234c649)

When uploading a media file, it's difficult to know what filetypes are allowed.

**Comment by pathartl** [comment]
Will be fixed in the next release. We currently cannot process .ico files, so the uploader has been restricted to .jpg,.jpeg,.png,.gif
