### ISSUE TITLE
Unable to select another drive for Uploads

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#50]
Unable to select another drive for Uploads
![msedge_XVytH2AuQl](https://github.com/LANCommander/LANCommander/assets/5581855/f81ae88f-bb88-479a-90ec-ba7b2b824ad5)

**Comment by pathartl** [comment]
The file manager currently doesn't support other drives. I believe you should be able to manually type in the drive, or set it by editing Settings.yml

**Comment by pathartl** [comment]
Other local drives (not network drives) will be selectable in 0.3.4.
