### ISSUE TITLE
Scripts not importing YamlDotNet.dll

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#53]
Installing Playnite with the Installer, rather than the portable install, it separates parts of the files between Appdata/Roaming and Appdata/Local. 

I'm assuming this is so that the app can be installed for multiple users but the customizable items (like extensions), are per-logged in user.

![image](https://github.com/LANCommander/LANCommander/assets/5581855/565ce32d-e455-4e8f-bf37-37d582e4bc74)

A quick temporary fix for this is editing the .psd1 file to reference the new location:
![image](https://github.com/LANCommander/LANCommander/assets/5581855/caef7f82-df54-49ab-ac26-e06fceeed209)

**Comment by pathartl** [comment]
Should be fixed in 0.4.0
