### ISSUE TITLE
[bug] PC Client, no games on first launch

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#74]
When launching the client and logging in for the first time, this is the screen:

![image](https://github.com/LANCommander/LANCommander/assets/5581855/0dfddecf-258e-4d46-9acd-6fe8d8784691)

It took a bit of messing with it to get the games to appear.

https://github.com/LANCommander/LANCommander/assets/5581855/73c9d706-ada4-4577-b3b2-07b54117089d

**Comment by pathartl** [comment]
Fixed in 0.8.5
