### ISSUE TITLE
[Enhancement] PC Client no collections

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#77]
If there are no collections on the server, the client should just not show any collections and just automatically show everything rather than having a single collection of "Uncategorized" that needs to be expanded every time.

**Comment by pathartl** [comment]
Will be included in the v0.8.4 release shortly

**Comment by miketweaver** [comment]
Tested v0.8.4, I'm not seeing any change?


https://github.com/LANCommander/LANCommander/assets/5581855/b73b96ef-10f0-4119-8bcc-ba8fe33ccc92

**Comment by pathartl** [comment]
Hm, I have a way to fix it, but temporarily you will probably need to unblock the following files:
- `Crc32.NET.dll`
- `Microsoft.Extensions.Logging.Abstractions.dll`
- `RestSharp.dll`
- `Semver.dll`
- `SharpCompress.dll`
- `System.Management.Automation.dll`

Alternatively, extract the release with something other than Windows Explorer.

**Comment by miketweaver** [comment]
I extracted with 7zip and the files came unblocked. I still don't see the change.

https://github.com/LANCommander/LANCommander/assets/5581855/3b0a2ca6-ffcb-4396-bcda-f16a5459963b

**Comment by pathartl** [comment]
Sorry that was meant to be a comment on #80

**Comment by pathartl** [comment]
Fixed in 0.8.5
