### ISSUE TITLE
[bug] PC Client powershell scripts not working

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#80]
When installing a game with a simple script like this:

```
New-Item -ItemType Directory -Force -Path "$env:APPDATA\EMUSETTINGS\settings"

# Write contents of a string to a file
Set-Content "$env:APPDATA\EMUSETTINGS\settings\account_name.txt" "$NewPlayerAlias"
```

I get these errors flash really fast. (I had to screen record and step through frame by frame to see it)

![image](https://github.com/LANCommander/LANCommander/assets/5581855/cd77dde8-ccbc-49bc-ac32-254c54d36859)

**Comment by pathartl** [comment]
Can you provide the hash of the `LANCommander.PowerShell.dll` file in the directory? I cannot replicate this one using a fresh download, unfortunately.

**Comment by miketweaver** [comment]
![image](https://github.com/LANCommander/LANCommander/assets/5581855/4a6e318b-06a8-40ae-9267-7228297b2527)

**Comment by miketweaver** [comment]
I dug into the error code a bit:
https://kb.yworks.com/article/736/Build-fails-with-Operation-not-supported-and-Exception-from-HRESULT-0x80131515

`HRESULT: 0x80131515`

I found that, after extracting the folder, it had the files marked an the "Internet Zone"

![image](https://github.com/LANCommander/LANCommander/assets/5581855/4491e93b-06da-45c2-906c-7fb2b8dcbe7d)

After deleting the folder, unblocking it, and re-extracting it, the issue goes away. This workaround seems to work, but it could be pretty annoying durning a LAN to try to get everyone to do this. Building an installer might fix this issue but I'm sure there are other ways too.

**Comment by pathartl** [comment]
That would make sense. PowerShell would block the DLL from being imported as a module due to this security feature. This might be something I can check on start of the client and fix.

**Comment by pathartl** [comment]
Found more info about this, Windows actually stores this information in NTFS alternate data streams. It seems that I have not encountered this in my testing because the Windows Explorer ZIP decompression functionality creates the `Zone.Identifier` ADS when extracting files, but NanaZip/7Zip does not. More information about this ADS:
http://mikehadlow.blogspot.com/2011/07/detecting-and-changing-files-internet.html

**Comment by miketweaver** [comment]
Tested v0.8.4, this error still occurs but this time on a different file:
![image](https://github.com/LANCommander/LANCommander/assets/5581855/5a9dcbc3-404d-4f55-aeaf-80e3918fbb24)

**Comment by pathartl** [comment]
Is `LANCommander.PowerShell.dll` still being blocked?

**Comment by miketweaver** [comment]
No, it looks unblocked.

![image](https://github.com/LANCommander/LANCommander/assets/5581855/4ab27f36-7a0a-42d8-b801-c3b41da55de7)
