### ISSUE TITLE
Feature Request: Other scraper than IGDB

### ISSUE THREAD

**Issue by 0P3N50URC3-F0R3V3R** [LANCommander/LANCommander#87]
Can you add support for more scrapers on LanCommander other than IGDB?  I dont want mess around with twitch, also in playnite there is IGDB but you dont need to create accounts and whatnot in that you can freely scrape the games... Why this is not a feature in this without any registration and such? Can you add other platform support for it? Like Steam or similar like in playnite? I can scrape in playnite if i want i know, but i want to deploy the games with the media on lan to wont need playnite to go thru scraping automaticly...

**Comment by pathartl** [comment]
I believe Playnite hosts their own IGDB dataset, and then the launcher accesses data through that. I didn't want to spin up a service for that. The only other option is to bundle an API key, which can get abused and is going to get rate limited.

MobyGames is another service that I've eyed, but have not done the actual work to start implementing. It would also require a registered account.

As a side note: the Playnite extension will be deprecated after v0.9.0. More information:
https://www.patreon.com/posts/v0-9-0-updates-109003781

**Comment by 0P3N50URC3-F0R3V3R** [comment]
>As a side note: the Playnite extension will be deprecated 

![star-wars-surprise](https://github.com/user-attachments/assets/87f0ae3a-6e03-46ee-bbba-b5483d12d8af)

NICE!
