### ISSUE TITLE
Feature Request - Multiple upload folders

### ISSUE THREAD

**Issue by 0P3N50URC3-F0R3V3R** [LANCommander/LANCommander#97]
I am very sorry if someone requested this before, but... Is there any way to add multiple upload archive locations? If not then it would be a great function to able to...  EG: I have a 500GB HDD and a 1T HDD full of games, but i cannot use them as one, but i can only specify one archive upload location...

Is this a possible feature request? 
For example if you are uploading a zip you would be able to chose wich folder you want to use if you previously added one in the settings... (1 folder on 1T hdd and 1 Folder on 500G)

**Comment by miketweaver** [comment]
It would probably be better if your OS handled this.

Storage Spaces in windows:
https://support.microsoft.com/en-us/windows/storage-spaces-in-windows-b6c8b540-b8d8-fb8a-e7ab-4a75ba11f9f2

Or overlayfs in linux:
https://wiki.archlinux.org/title/Overlay_filesystem

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Better than a simple dropdown menu and an extra DB entry? I dont want to create raids, virtual storages crosslinks mirrors ect.. ect... ect...  For example i have a Jellyfin server, it can do it... Why on earth trhis would be more simple??? 
You can add more storages... I dont think is is more simple. At all. On linux perhaps but not on windows.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Better than a simple dropdown menu and an extra DB entry? I dont want to create raids, virtual storages crosslinks mirrors ect.. ect... ect... For example i have a Jellyfin server, it can do it... Why on earth trhis would be more simple???
You can add more storages... I dont think is is more simple. At all.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> It would probably be better if your OS handled this.
> 
> Storage Spaces in windows: https://support.microsoft.com/en-us/windows/storage-spaces-in-windows-b6c8b540-b8d8-fb8a-e7ab-4a75ba11f9f2

Better than a simple dropdown menu and an extra DB entry? I dont want to create raids, virtual storages crosslinks mirrors ect.. ect... ect... For example i have a Jellyfin server, it can do it... Why on earth trhis would be more simple???
You can add more storages... I dont think is is more simple. At all. Also it is better to handle when one HDD is dead for some reason , so no not practical from the os side...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> It would probably be better if your OS handled this.
> 
> Storage Spaces in windows: https://support.microsoft.com/en-us/windows/storage-spaces-in-windows-b6c8b540-b8d8-fb8a-e7ab-4a75ba11f9f2

Better than a simple dropdown menu and an extra DB entry? I dont want to create raids, virtual storages crosslinks mirrors ect.. ect... ect... For example i have a Jellyfin server, it can do it... you can simply add more storage folders.  Why on earth trhis would be more simple??? This request is not so different either

You can add more storages... I dont think is is more simple. At all. Also it is better to handle when one HDD is dead for some reason , so no not practical from the os side...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> It would probably be better if your OS handled this.
> 
> Storage Spaces in windows: https://support.microsoft.com/en-us/windows/storage-spaces-in-windows-b6c8b540-b8d8-fb8a-e7ab-4a75ba11f9f2

Better than a simple dropdown menu and an extra DB entry? I dont want to create raids, virtual storages crosslinks mirrors ect.. ect... ect... For example i have a Jellyfin server, it can do it... you can simply add more storage folders.  Why on earth that would be more simple??? This request is not so different either, also there is a lot of problem in merged/raided/ect.. drives... a lot more... especially with error handling.. so no not practical.You should be able to add more storages... I dont think anything else is more simple. At all. Also it is better to handle when one HDD is dead for some reason , opr you need to change it, and you can get a lot of headache with that... so no not practical from the os side... Also i dont have EXTRA drives... for a thing like that(1.g. Storage spaces) XD Impractical that you need to have extra hdd's XD Also expensive, when it can be solved much more simple. Also impractical when i move data, change SSD/HDD's and such... in every way... More folder would be more simple. More practical.

**Comment by pathartl** [comment]
This is something that will come in future versions, but much of the web UI has to be reworked in order to support it. Keeping this open for future development tracking.

**Comment by pathartl** [comment]
![image](https://github.com/user-attachments/assets/52e4f985-cd5c-4e53-8d74-2ab4f57c2a0f)
![image](https://github.com/user-attachments/assets/e5d06b83-4a1b-4b99-aedf-daab7730410b)

There are some minor bugs to work out, but this will be in the v1.1.0 release.
